spring:
 datasource:
  url: jdbc:mysql://localhost:3306/db_account?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: abcd
  driver-class-name: com.mysql.cj.jdbc.Driver