spring:
  mvc:
#    #    设置静态资源目录访问时要加的前缀
#    static-path-pattern: /img/**
    hiddenmethod:
      filter:
#        开启post请求处理delete和put请求
        enabled: true
#  web:
#    resources:
##      static-locations: 设置静态资源地址
##        设置静态资源能不能被访问
#      add-mappings: true
#      cache:
##        设置静态资源访问存在时间，s
#        period: 1000

#配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/text?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置mapper.xml文件路径
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

server:
  port: 8833